name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esp-docs cairosvg
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build documentation
        working-directory: docs
        run: |
          build-docs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docs\_build\en\generic\html
          force_orphan: true
          enable_jekyll: false

      - name: Clean workspace
        run: |
          git clean -fdx
            
      - name: Debug - Check deployment
        run: |
          # Fetch and check gh-pages content
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of gh-pages branch root:"
          ls -la
          echo "Checking for index.html:"
          test -f index.html && echo "index.html exists" || echo "index.html is missing"