name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esp-docs cairosvg
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build documentation
        working-directory: docs
        run: |
          build-docs build

          - name: List build contents
          run: |
            echo "Contents of HTML directory:"
            ls -la docs/_build/en/generic/html/
  
      - name: Prepare for deployment
        run: |
          # Create .nojekyll file
          touch docs/_build/en/generic/html/.nojekyll
          # Ensure all files are readable
          chmod -R a+r docs/_build/en/generic/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docs\_build\en\generic\html
          force_orphan: true
          enable_jekyll: false
